swear_jar/urls.py
from django.conf.urls import url

from . import views

app_name = 'swear_jar'

urlpatterns = [
    url(r'^test/$', views.test, name='test'),
    url(r'^$', views.welcome, name='homepage'),
    url(r'^join/$', views.join_swear_jar, name='join_swear_jar'),
    url(r'^create_organisation/$', views.create_organisation_form, name='create_organisation'),
    url(r'^created_organisation/$', views.created_organisation, name='created_organisation'),
    url(r'^search_organisation/$', views.search_organisation, name='search_organisation'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^log/$', views.log, name='logs'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^results/$', views.organisation_results, name='results'),
    url(r'^(?P<organisation_id>[0-9]+)/create_player/$', views.create_player_form, name='create_player'),
    url(r'^create_player/$', views.create_player_form, name='create_player_orgaless'),
    url(r'^(?P<organisation_id>[0-9]+)/created_player/$', views.created_player, name='created_player'),
    url(r'^created_player/$', views.created_player, name='created_player_orgaless'),
    url(r'^organisation_admin/$', views.organisation_admin, name='organisation_admin'),
    url(r'^change_player/$', views.change_player_status, name='change_player'),
    url(r'^denounce/$', views.denounce, name='denounce_curse'),
    url(r'^denounced/$', views.denounced, name='denounced_curse'),
    url(r'^regroup_curse/$', views.regroup_curse, name='regroup_curse'),
    url(r'^reported_curse/$', views.reported_curse, name='reported_curse'),
    url(r'^player_graph/$', views.player_graph, name='player_graph'),
    url(r'^player_home/$', views.player_home, name='player_home'),
    url(r'^player_edit/$', views.player_edit, name='player_edit'),
    url(r'^player_edited/$', views.player_edited, name='player_edited'),
    url(r'^player_change_password/$', views.player_change_password, name='player_change_password'),
    url(r'^player_bank/$', views.player_bank, name='player_bank'),
    url(r'^player_bank_paid/$', views.player_paid_bank, name='player_bank_paid'),
    url(r'^api/search_organisation$', views.api_search, name='api_search_orga'),
    url(r'^api/join_organisation/(?P<organisation_id>[0-9]+)$', views.api_join_organisation,
        name='api_join_organisation'),
    url(r'^api/accept_curse$', views.api_accept_curse, name='api_accept_curse'),
    url(r'^api/reject_curse$', views.api_reject_curse, name='api_reject_curse'),
]

swear_jar/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Organisation(models.Model):
    name = models.CharField(max_length=200)


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    organisation = models.ForeignKey('Organisation')
    email = models.EmailField()
    admin = models.BooleanField(default=False)
    admited = models.BooleanField(default=False)
    bank_credit = models.FloatField(default=.0)


class Curse(models.Model):
    curse = models.CharField(max_length=500)
    author = models.ForeignKey('Player')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)


class ReportedCurse(models.Model):
    curse = models.CharField(max_length=500)
    context = models.CharField(max_length=500)
    author = models.ForeignKey('Player', related_name='%(class)s_author')
    reporter = models.ForeignKey('Player', related_name='%(class)s_reporter')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    

class BankPaid(models.Model):
    amount = models.FloatField()
    author = models.ForeignKey('Player')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

swear_jar/templates/swear_jar/admin_board.html
{% extends "swear_jar/header.html" %}
{% block body %}

<script>
function noteResult(player_id, role) {
  result = "Noted !"
  var td_join = document.getElementById(player_id + '_' + role);
  while (td_join.firstChild) {
    td_join.removeChild(td_join.firstChild)
  }
  td_join.innerHTML = "Done";
}

function changePlayerStatus(player_id, role) {
  var post_request = {'player_id': player_id, 'status': role};
  $.post("{% url 'swear_jar:change_player' %}", post_request, function(data, status, xhr) {
    noteResult(player_id, role);
  })
}

function csrfSafeMethod(method) {
  // these HTTP methods do not require CSRF protection
  return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$(document).ready(function() {
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        }
            }
    });
});
</script>

<section class="col-sm-12">
  <table class="table table-bordered table-hover table-condensed">
    <caption>Players to join</caption>
    <thead>
      <tr>
        <th>Username</th>
        <th>Join organisation</th>
        <th>Make admin</th>
      </tr>
    </thead>
    <tbody>
  {% for player in players_outside %}
    <tr>
      <td>{% if player.name %} {{ player.name }} {% else %} {{ player.user.username }} {% endif %}</td>
      <td id="{{ player.id }}_inside"> <button onclick="changePlayerStatus({{ player.id }}, 'inside')">Join</button></td>
      <td id="{{ player.id }}_admin"> <button onclick="changePlayerStatus({{ player.id }}, 'admin)">Make admin</button></td>
    </tr>
  {% endfor %}
  {% for player in players_inside %}
    <tr>
      <td>{% if player.name %} {{ player.name }} {% else %} {{ player.user.username }} {% endif %}</td>
      <td>Already joined</td>
      <td id="{{ player.id }}_admin"> <button onclick="changePlayerStatus({{ player.id }}, 'admin')">Make admin</button></td>
    </tr>
  {% endfor %}
     </tbody>
  </table>
</section>

{% endblock %}

swear_jar/templates/swear_jar/bank.html
{% extends "swear_jar/header.html" %}
{% block body %}
  <div class="col-lg-8">
    {{ player.name }} has credit {{ player.bank_credit }}
  </div>
  <form action="{% url 'swear_jar:player_bank_paid' %}" method="post" class="col-lg-8">
  {% csrf_token %}
  <label for="amount_paid">Amount</label>
  <input type="number" name="amount_paid" step="0.01" class="form-control">
  <button>Pay bank (virtually)</button>
  </form>
{% endblock %}

swear_jar/templates/swear_jar/bank_paid.html
{% extends "swear_jar/header.html" %}
{% block body %}
<div class="col-lg-12">
  {{ bank_paid.author.name }} credited {{ bank_paid.amount }}
</div>
{% endblock %}

swear_jar/templates/swear_jar/bu_search_organisation.html
{% extends "swear_jar/header.html" %}
{% block body %}

Search an organisation<br\>

<ul>
  <li>Organisation name: <input type="text" name="organisation_name" /> </li>
</ul>
<button type="submit" id="button_search">Search!</button> 

{% csrf_token %}

<div id='div_orga_search_res'>
  rien
</div>
<script>
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = jQuery.trim(cookies[i]);
	// Does this cookie string begin with the name we want?
	if (cookie.substring(0, name.length + 1) == (name + '=')) {
	  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
	}
      }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken')

function csrfSafeMethod(method) {
  // these HTTP methods do not require CSRF protection
  return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

function sameOrigin(url) {
  // test that a given url is a same-origin URL
  // url could be relative or scheme relative or absolute
  var host = document.location.host; // host + port
  var protocol = document.location.protocol;
  var sr_origin = '//' + host;
  var origin = protocol + sr_origin;
  // Allow absolute or scheme relative URLs to same origin
  return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
    (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
    // or any other URL that isn't scheme relative or absolute i.e relative.
    !(/^(\/\/|http:|https:).*/.test(url));
}

$.ajaxSetup({
  beforeSend: function(xhr, settings) {
    if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
    // Send the token to same-origin, relative URLs only.
    // Send the token only if the method warrants CSRF protection
    // Using the CSRFToken value acquired earlier
    xhr.setRequestHeader("X-CSRFToken", csrftoken);
    }
  }
});


$(document).ready(function(){
  $("button").click(function(){
    alert("sending post request")
    $.post("api/search_organisation", post_request, function(data, status, xhr) {
       alert("Data: " + data + "\nStatus: " + status);
    });
  });
});
</script>
</head>
<body>

  <div id="div1"><h2>Let jQuery AJAX Change This Text</h2></div>

  <button>Get External Content</button>

</body>
</html>

<script>
  $(document).ready(function(){
     $("p").click(function(){
        $(this).hide();
     });
  });
</script>
</head>
<body>

  <p>If you click on me, I will disappear.</p>
  <p>Click me away!</p>
  <p>Click me too!</p>
  
<script>
  $(document).ready(function(){
    $("button").click(function() {
        alert("Data: " + data + "\nStatus: " + status);
    });
  });
  /*
  $(document).ready(function(){
    $(".main").on('click', '.button_search', function() {
      $.get("./api/search_organisation", function(data, status){
        alert("Data: " + data + "\nStatus: " + status);
      });
    });
  });
  $(document).ready(function(){
    $("button_search").click(function() {
      $.get("./api/search_organisation", function(data, status){
        alert("Data: " + data + "\nStatus: " + status);
      });
    });
  });
  */
  /*
  var orga_names = get_data_from_api()
  // ['Dolead', 'Maison Gambetta', 'Tata Yoyo']
  div_results = document.getElementById('div_orga_search_res')
  
  var ul = document.createElement('ul')
  var li, button;
  len = orga_names.length
  for (var i=0, i < len; i++) {
      li = document.createElement('li')
      li.appendChild(document.createTextNode(orga_names[i]))
      button = document.createElement('input')
      button.type = "submit"
      button.value = "Join organisation"
      button.id = "button_" + orga_names[i]
      ul.appendChild(button)
      ul.appendChild(li)
  }
  div_results.appendChild(ul)
  */
</script>

{% endblock %}

swear_jar/templates/swear_jar/create_organisation.html
{% extends "swear_jar/header.html" %}
{% block body %}

<form action="{% url 'swear_jar:created_organisation' %}" method="post" class="col-lg-4">
  {% csrf_token %}
  <legend>Create organisation</legend>
    <div class="form-group">
      <label class="col-md-4 control-label" for="organisation_name">Name of organisation</label>
      <div class="col-md-6  inputGroupContainer">
        <div class="input-group">
          <input type="text" name="organisation_name" class="form-control">
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
	<button>Create organisation</button>
      </div>
    </div>
</form>

{% endblock %}

swear_jar/templates/swear_jar/create_player.html
{% extends "swear_jar/header.html" %}
{% block body %}


<div class="container">
  {% if organisation %}
    <form action="{% url 'swear_jar:created_player' organisation.id %}" method="post" class="col-lg-4" id="form_create_player">
  {% else %}
    <form action="{% url 'swear_jar:created_player_orgaless' %}" method="post" class="col-lg-4" id="form_create_player">
  {% endif %}
  {% csrf_token %}
    <legend>Create new player {%if organisation %}for {{ organisation.name }} {% endif %}</legend>
    <div class="form-group">
      <label class="col-md-4 control-label">Your username</label>
      <div class="col-md-6  inputGroupContainer">
        <div class="input-group">
          <input name="username" class="form-control"  type="text">
          <span class="glyphicon form-control-feedback"></span>
          <span class="help-block with-errors"></span>
        </div>
      </div>
    </div>
  
  
    <div class="form-group">
      <label class="col-md-4 control-label">Your e-Mail</label>
      <div class="col-md-6  inputGroupContainer">
        <div class="input-group">
          <input name="email" class="form-control"  type="text">
          <span class="glyphicon form-control-feedback"></span>
          <span class="help-block with-errors"></span>
        </div>
      </div>
    </div>
  
  
    <div class="form-group has-feedback">
      <label for="password"  class="col-md-4 control-label">Password</label>
      <div class="col-md-6  inputGroupContainer">
        <div class="input-group">
          <input class="form-control" id="userPw" type="password"
  	   name="password" data-minLength="5"
  	   data-error="some error"
  	   required/>
          <span class="glyphicon form-control-feedback"></span>
          <span class="help-block with-errors"></span>
        </div>
      </div>
    </div>
  
    <div class="form-group has-feedback">
      <label for="confirmPassword"  class="col-md-4 control-label">Confirm password</label>
      <div class="col-md-6  inputGroupContainer">
        <div class="input-group">
          <input class="form-control {$borderColor}" id="userPw2" type="password"
  	       name="confirmPassword" data-match="#confirmPassword" data-minLength="5"
  	       data-match-error="some error 2"
  	       required/>
          <span class="glyphicon form-control-feedback"></span>
          <span class="help-block with-errors"></span>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
	<button>Create player</button>
      </div>
    </div>
  </form>
</div>


<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js'></script>

<script type="text/javascript">

  $(document).ready(function() {
    $('#form_create_player').bootstrapValidator({
      // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
      feedbackIcons: {
        valid: 'glyphicon glyphicon-ok',
        invalid: 'glyphicon glyphicon-remove',
        validating: 'glyphicon glyphicon-refresh'
      },
        fields: {
          username: {
            validators: {
            }
          },
          email: {
            validators: {
              notEmpty: {
                message: 'Please supply your email address'
              },
              emailAddress: {
                message: 'Please supply a valid email address'
              }
            }
          },
          password: {
            validators: {
              identical: {
                field: 'confirmPassword',
                message: 'Confirm your password below - type same password please'
              }
            }
          },
          confirmPassword: {
            validators: {
              identical: {
                field: 'password',
                message: 'The password and its confirm are not the same'
              }
            }
          },
        }
      })


  .on('success.form.bv', function(e) {
    $('#success_message').slideDown({ opacity: "show" }, "slow") // Do something ...
      $('#reg_form').data('bootstrapValidator').resetForm();

      // Prevent form submission
      e.preventDefault();

      // Get the form instance
      var $form = $(e.target);

      // Get the BootstrapValidator instance
      var bv = $form.data('bootstrapValidator');

      // Use Ajax to submit form data
      $.post($form.attr('action'), $form.serialize(), function(result) {
        console.log(result);
      }, 'json');
  });
});

</script>
{% endblock %}

swear_jar/templates/swear_jar/detail.html
{% extends "swear_jar/header.html" %}
{% block body %}
    <h1>{{ organisation.name }}</h1>
    
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
    <form action="{% url 'swear_jar:denounce' organisation.id %}" method="post" class="col-lg-8">
    {% csrf_token %}
    {% for player in organisation.player_set.all %}
        <input type="radio" name="player" id="player{{forloop.counter }}" value="{{ player.id }}" />
        <label for="player{{ forloop.counter }}">{{ player.name }}</label> <br/>
    {% endfor %}
    <input type="submit" value="denounce">
    </form>
{% endblock %}

swear_jar/templates/swear_jar/edit_player.html
{% extends "swear_jar/header.html" %}
{% block body %}
<div class="container">
  <form action="{% url 'swear_jar:player_edited' %}" method="post" class="col-lg-4">
  {% csrf_token %}
  
  <legend>User information</legend>
  <div class="form-group has-feedback">
    <label for="name" class="col-md-3 control-label">Display name</label>
    <div class="inputGroupContainer">
      <div class="input-group">
        <input type="text" name="name" class="form-control" placeholder="{{ request.user.player.name }}">
      </div>
    </div>
  </div>
  <div class="form-group has-feedback">
    <label for="name" class="col-md-3 control-label">Email</label>
    <div class="inputGroupContainer">
      <div class="input-group">
        <input type="text" name="email" class="form-control" placeholder="{{ request.user.player.email }}">
      </div>
    </div>
  </div>
    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
	<button>Change profile</button>
      </div>
    </div>
  </form>
</div>

<div class="container">
  <form action="{% url 'swear_jar:player_change_password' %}" method="post" class="col-lg-4" id="change_password">
  {% csrf_token %}
  
  <legend>Change password</legend>
  <div class="form-group has-feedback">
    <label for="old" class="col-md-3 control-label">Current password</label>
    <div class="inputGroupContainer">
      <div class="input-group">
        <input type="password" name="old" class="form-control" placeholder="Current password">
      </div>
    </div>
  </div>
  
  <div class="form-group has-feedback">
    <label for="password"  class="col-md-3 control-label">New password</label>
    <div class="inputGroupContainer">
      <div class="input-group">
        <input class="form-control" id="userPw" type="password" placeholder="password"
     name="password_new" data-minLength="5"
     data-error="some error"
     required/>
        <span class="glyphicon form-control-feedback"></span>
        <span class="help-block with-errors"></span>
      </div>
    </div>
  </div>
  
  <div class="form-group has-feedback">
    <label for="confirmPassword"  class="col-md-3 control-label">Confirm Password</label>
    <div class="inputGroupContainer">
      <div class="input-group">
        <input class="form-control {$borderColor}" id="userPw2" type="password" placeholder="Confirm password"
         name="password_repeat" data-match="#confirmPassword" data-minLength="5"
         data-match-error="some error 2"
         required/>
        <span class="glyphicon form-control-feedback"></span>
        <span class="help-block with-errors"></span>
      </div>
    </div>
  </div>
    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
	<button>Change password</button>
      </div>
    </div>
  </form>
</div>

<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js'></script>

<script type="text/javascript">

  $(document).ready(function() {
    $('#change_password').bootstrapValidator({
      // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
      feedbackIcons: {
        valid: 'glyphicon glyphicon-ok',
        invalid: 'glyphicon glyphicon-remove',
        validating: 'glyphicon glyphicon-refresh'
      },
        fields: {
          password_repeat: {
            validators: {
              identical: {
                field: 'password_new',
                message: 'The password and its confirm are not the same'
              }
            }
          },
          password_new: {
            validators: {
              identical: {
                field: 'password_repeat',
                message: 'Confirm your password below - type same password please'
              }
            }
          },
        }
      })


  .on('success.form.bv', function(e) {
    $('#success_message').slideDown({ opacity: "show" }, "slow") // Do something ...
      $('#reg_form').data('bootstrapValidator').resetForm();

      // Prevent form submission
      e.preventDefault();

      // Get the form instance
      var $form = $(e.target);

      // Get the BootstrapValidator instance
      var bv = $form.data('bootstrapValidator');

      // Use Ajax to submit form data
      $.post($form.attr('action'), $form.serialize(), function(result) {
        console.log(result);
      }, 'json');
  });
});

  </script>
{% endblock %}

swear_jar/templates/swear_jar/login.html
{% extends "swear_jar/header.html" %}
{% block body %}
<div>
  <form action="{% url 'swear_jar:logs' %}" method="post" class="col-lg-4">
    {% csrf_token %}
    <legend>Login</legend>
    <label for="username">User name</label>
    <input type="text" name="username" class="form-control">
    <label for="password">Password</label>
    <input type="password" name="password" class="form-control">
    <button>Log</button>
  </form>
  {% if errors %} {{ errors }} {% endif %}
</div>

{% endblock %}

swear_jar/templates/swear_jar/not_admin.html
{% extends "swear_jar/header.html" %}
{% block body %}
<div class="col-sm-12">
You are not admin of {{ organisation.name }}.
</div>

{% endblock %}

swear_jar/templates/swear_jar/player_home.html
{% extends "swear_jar/header.html" %}
{% block body %}

<div class="row">
  <div class="container col-lg-6">
    {% include "javascript/graphs.html" %}
  </div>
  <div class="container col-lg-6">
    {% include "forms/denounce.html" %}
  </div>
  <div class="container col-lg-6">
    {% include "forms/regroup_swear.html" %}
  </div>
</div>

{% endblock %}

swear_jar/templates/swear_jar/results.html
{% extends "swear_jar/header.html" %}
{% block body %}
<div class="col-sm-6">
  <table class="table table-bordered table-hover table-condensed">
    <caption>Curses in {{ organisation.name }}</caption>
    <thead>
      <tr>
        <th>Player name</th>
        <th>#Curses</th>
        <th>Bank account</th>
      </tr>
    </thead>
    <tbody>
  {% for player in organisation.player_set.all %}
    <tr>
      <td>{{ player.name }}</td>
      <td>{{ player.curse_set.count }}</td>
      <td>{{ player.bank_credit }}</td>
    </tr>
  {% endfor %}
  </table>
</div>
<div class="col-sm-12">
SwearJar of {{ organisation.name }} should contain {{ bank_orga_theo }} euros. It currently has {{ bank_orga }} euros.
</div>


{% endblock %}

swear_jar/templates/swear_jar/welcome.html
{% extends "swear_jar/header.html" %}
{% block body %}

{% include "swear_jar/am_chart_header.html" %}
<script src="https://www.amcharts.com/lib/3/pie.js"></script>

<div class="container">
  <h1>Welcome to SwearJar</h1>
      <div class="container">
	<h2>What's the point</h2>
        This site wants to improve working conditions by reducing swearwords. Each time someone, in the open space, swears or yell something, he has to put 0.10$ in your office SwearJar. This money will be used to buy cookies, beer or an overhead projector.	
      </div>
      <div class="container">
	<h2>Any cool feature?</h2>
	  <div>
          Not much. We store the information. We do make nice graphs of a person's swearing habits.
	  </div>
	  <script>
	     var chartWeeklyData = [{'week': '2016-08-22', 'curses': 7}, {'week': '2016-08-29', 'curses': 1}, {'week': '2016-09-05', 'curses': 0}, {'week': '2016-09-12', 'curses': 0}]; 

            AmCharts.ready(function () {
              // --- Weekly graph ---
              var chartWeekly = AmCharts.makeChart("chart_week_div", {
                 "balloon":{
                   "fixedPosition":true
                 },
                 "categoryAxis": {
                   "gridCount": 4,
                   "gridPosition": "start",
                   "title": "Week",
                 },
                 "categoryField": "week",
                 "dataProvider": [
	           {'week': '2016-08-22', 'curses': 10},
	           {'week': '2016-08-29', 'curses': 12},
	           {'week': '2016-09-05', 'curses': 11},
	           {'week': '2016-09-12', 'curses': 8}],
                 "export": {
                   "enabled": true
                 },
                 "graphs": [{
                   "valueField": "curses",
                   "balloonText": "Week [[category]]: <b>[[value]]</b>",
                   "bullet": "round",
                   "lineThickness": 2,
                   "type": "smoothedLine", 
                 }],
                 "labelText": "[[title]]: [[value]]",
                 "titleField": "curse",
                 "titles": [{"text": "Number of curses by week"}],
                 "type": "serial",
                 "valueAxes": [{"title": "Number of curses"}],
              });
              chartWeekly.invalidateSize();
          
              var chart2 = AmCharts.makeChart("chart_tot_count_div", {
                "type": "pie",
                "theme": "light",
                "titles": [{"text": "Curses count"}],
                "dataProvider": [
	          {"curse": "fuck", "number": 16},
	          {"curse": "Banged table", "number": 15},
	          {"curse": "shit", "number": 10},
	        ],
                "valueField": "number",
                "titleField": "curse",
                "balloon":{
                  "fixedPosition":true
                },
                "labelText": "[[title]]: [[value]]",
                "export": {
                  "enabled": true
                },
                "startDuration": 0
             });
	     
             var chartDaily = AmCharts.makeChart("chart_weekday_div", {
                "balloon":{
                  "fixedPosition":true
                },
                "categoryAxis": {
                  "gridCount": 7,
                  "gridPosition": "start",
                  "title": "Weekday",
                },
                "categoryField": "weekday",
                "dataProvider": [
             	     {'weekday': 'Monday', 'curses': 6},
             	     {'weekday': 'Tuesday', 'curses': 7},
             	     {'weekday': 'Wednesday', 'curses': 8},
             	     {'weekday': 'Thursday', 'curses': 11},
             	     {'weekday': 'Friday', 'curses': 9},
             	     {'weekday': 'Saturday', 'curses': 0},
             	     {'weekday': 'Sunday', 'curses': 0},
             	     ],
                "export": {
                  "enabled": true
                },
                "graphs": [{
                  "valueField": "curses",
                  "balloonText": "Day [[category]]: <b>[[value]]</b>",
                  "bullet": "round",
                  "lineThickness": 2,
                  "type": "smoothedLine", 
                }],
                "labelText": "[[title]]: [[value]]",
                "titleField": "curse",
                "titles": [{"text": "Number of curses by Weekday"}],
                "type": "serial",
                "valueAxes": [{"title": "Number of curses"}],
             });
  
             // AXES
             chartDaily.invalidateSize();
            });
	  </script>
          <div id="chart_tot_count_div" class="col-xs-4 col-sm-3 col-md-2" style="width:500px;height:300px;"></div>
          <div id="chart_week_div" class="col-xs-4 col-sm-3 col-md-2" style="width:500px;height:300px;"></div>
          <div id="chart_weekday_div" class="col-xs-4 col-sm-3 col-md-2" style="width:500px;height:300px;"></div>
      </div>
      <div class="container">
	<h2>How do I join?</h2>
	<a href={% url 'swear_jar:join_swear_jar' %}>Click here!</a>
      </div>
</div>

{% endblock %}