swear_jar/urls.py
from django.conf.urls import url

from . import views

app_name = 'swear_jar'

urlpatterns = [
    url(r'^test/$', views.test, name='test'),
    url(r'^$', views.welcome, name='homepage'),
    url(r'^join/$', views.join_swear_jar, name='join_swear_jar'),
    url(r'^create_organisation/$', views.create_organisation_form, name='create_organisation'),
    url(r'^created_organisation/$', views.created_organisation, name='created_organisation'),
    url(r'^search_organisation/$', views.search_organisation, name='search_organisation'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^log/$', views.log, name='logs'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^results/$', views.organisation_results, name='results'),
    url(r'^(?P<organisation_id>[0-9]+)/create_player/$', views.create_player_form, name='create_player'),
    url(r'^create_player/$', views.create_player_form, name='create_player_orgaless'),
    url(r'^(?P<organisation_id>[0-9]+)/created_player/$', views.created_player, name='created_player'),
    url(r'^created_player/$', views.created_player, name='created_player_orgaless'),
    url(r'^organisation_admin/$', views.organisation_admin, name='organisation_admin'),
    url(r'^change_player/$', views.change_player_status, name='change_player'),
    url(r'^denounce/$', views.denounce, name='denounce_curse'),
    url(r'^denounced/$', views.denounced, name='denounced_curse'),
    url(r'^regroup_curse/$', views.regroup_curse, name='regroup_curse'),
    url(r'^reported_curse/$', views.reported_curse, name='reported_curse'),
    url(r'^player_graph/$', views.player_graph, name='player_graph'),
    url(r'^player_home/$', views.player_home, name='player_home'),
    url(r'^player_edit/$', views.player_edit, name='player_edit'),
    url(r'^player_edited/$', views.player_edited, name='player_edited'),
    url(r'^player_change_password/$', views.player_change_password, name='player_change_password'),
    url(r'^player_bank/$', views.player_bank, name='player_bank'),
    url(r'^player_bank_paid/$', views.player_paid_bank, name='player_bank_paid'),
    url(r'^api/search_organisation$', views.api_search, name='api_search_orga'),
    url(r'^api/join_organisation/(?P<organisation_id>[0-9]+)$', views.api_join_organisation,
        name='api_join_organisation'),
    url(r'^api/accept_curse$', views.api_accept_curse, name='api_accept_curse'),
    url(r'^api/reject_curse$', views.api_reject_curse, name='api_reject_curse'),
]

swear_jar/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Organisation(models.Model):
    name = models.CharField(max_length=200)


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    organisation = models.ForeignKey('Organisation')
    email = models.EmailField()
    admin = models.BooleanField(default=False)
    admited = models.BooleanField(default=False)
    bank_credit = models.FloatField(default=.0)


class Curse(models.Model):
    curse = models.CharField(max_length=500)
    author = models.ForeignKey('Player')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)


class ReportedCurse(models.Model):
    curse = models.CharField(max_length=500)
    context = models.CharField(max_length=500)
    author = models.ForeignKey('Player', related_name='%(class)s_author')
    reporter = models.ForeignKey('Player', related_name='%(class)s_reporter')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    

class BankPaid(models.Model):
    amount = models.FloatField()
    author = models.ForeignKey('Player')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

swear_jar/templates/forms/denounce.html
<div class="container">
  <form action="{% url 'swear_jar:denounced_curse' %}" method="post" class="col-lg-6 col-md-6">
  {% csrf_token %}
  
  <legend>Who said what in {{ organisation.name }}</legend>
    <div class="form-group">
      <div class="container">
        <label class="col-md-2 control-label">Who ?</label>
      </div>
      <div class="container">
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group col-md-6 col-lg-6">
            <select name="player_id" class="form-control">
              {% for player in organisation.player_set.all %}
                <option value={{ player.id }}{% if player.id == request.user.player.id %} selected="selected"{% endif %}>{{ player.user.username }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="container">
        <label class="col-md-2 control-label">Said what ?</label>
      </div>
      <div class="container">
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group col-md-6 col-lg-6">
        	  <input type="text" name="curse_text" class="form-control">
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="container">
        <label class="col-md-2 control-label">Which context ?</label>
      </div>
      <div class="container">
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group col-md-6 col-lg-6">
        	  <input type="text" name="curse_context" class="form-control" placeholder="(optional)">
          </div>
        </div>
      </div>
    </div>
      <div class="form-group">
        <label class="col-md-6 control-label"></label>
        <div class="col-md-6">
  	  <button>Denounce curse</button>
        </div>
      </div>
  </form>
</div>

swear_jar/templates/forms/regroup_swear.html
<div class="container">
  <form action="{% url 'swear_jar:regroup_curse' %}" method="post" class="col-lg-6 col-md-6">
  {% csrf_token %}
  
  <legend>Change curse spelling</legend>
    <div class="form-group">
      <div class="container">
        <label class="col-md-2 control-label">Curse old spelling</label>
      </div>
      <div class="container">
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group col-md-6 col-lg-6">
            <select name="curse_old" class="form-control">
              {% for curse_text in curse_set %}
                <option value="{{ curse_text }}">{{ curse_text }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="container">
        <label class="col-md-2 control-label">New spelling</label>
      </div>
      <div class="container">
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group col-md-6 col-lg-6">
        	  <input type="text" name="curse_new" class="form-control">
          </div>
        </div>
      </div>
    </div>
    </div>
      <div class="form-group">
        <label class="col-md-6 control-label"></label>
        <div class="col-md-6">
  	  <button>Change curse</button>
        </div>
      </div>
  </form>
</div>